source "https://rubygems.org"

gem "bootsnap", require: false
gem "image_processing", "~> 1.2"
gem "kamal", require: false
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "rails", "~> 8.1.1"
gem "solid_cable"
gem "solid_cache"
gem "solid_queue"
gem "thruster", require: false
gem "tzinfo-data", platforms: %i[ windows jruby ]


group :development, :test do
  gem "brakeman", require: false
  gem "bundler-audit", require: false
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "factory_bot_rails" 
  gem "pry-rails"
  gem "pry"
  gem "rspec-rails"
  gem "rubocop-rails-omakase", require: false
end
